name: 'CI'

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        deno-version: [v1.x, 1.37.2, 1.38.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Deno ${{ matrix.deno-version }}
          uses: denoland/setup-deno@v1
          with:
            deno-version: ${{ matrix.deno-version }}

        - name: Deno Lint
          run: deno lint
          if: matrix.os == 'ubuntu-latest'

        - name: Deno Format
          run: deno fmt --check
          if: matrix.os == 'ubuntu-latest'

        - name: Deno Test
          run: deno task test

        - name: Deno Info
          run: deno info src/ini.ts
